name: 'Monitor Content Changes'
description: 'Monitors and reports changes to protected content'

inputs:
  issue-number:
    description: 'The issue number being monitored'
    required: true
  repository-owner:
    description: 'The owner of the repository'
    required: true
  token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: "composite"
  steps:
    - name: Monitor Changes
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const changeNotice = `## ⚠️ Content Change Detected

          The protected content of this issue has been modified.
          - The existing snapshot PR has been updated
          - Maintainers will review these changes
          
          @${inputs.repository-owner} Please review these changes.`;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: inputs.issue-number,
            body: changeNotice
          });
