name: Grant Application
description: Submit a grant application to Zcash Community Grants
title: Grant Application - (ID, Project Name)
labels:
- Grant Application
body:

- type: markdown
  attributes:
    value: '## Terms and Conditions'

- type: checkboxes
  id: terms_and_conditions_checkboxes
  attributes:
    label: Terms and Conditions
    description: Please review and accept all terms and conditions before proceeding
    options:
    - label: I agree to the [Grant Agreement]() terms if funded
    - label: I agree to [Provide KYC information]() if funded above $50,000 USD
    - label: I agree to disclose conflicts of interest
    - label: I agree to adhere to the [Code of Conduct]()
    - label: I agree to post request details on the [Community Forum]()
    - label: _Link to this issue on forum (do after application has been submitted)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Organization Details'

- type: input
  id: organization_details_name
  attributes:
    label: Organization Name
    description: Name of the organization or individual applying for the grant
  validations:
    required: true

- type: input
  id: organization_details_owners
  attributes:
    label: Application Owners (GitHub @Usernames)
    description: GitHub usernames of all individuals responsible for this application
  validations:
    required: true

- type: input
  id: organization_details_discovery
  attributes:
    label: How did you learn about Zcash Community Grants
    description: Help us understand how applicants discover our grant program
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Overview'

- type: input
  id: project_overview_name
  attributes:
    label: Project Name
    description: A brief, descriptive name for your project
  validations:
    required: true

- type: input
  id: project_overview_amount
  attributes:
    label: Requested Grant Amount (USD)
    description: Total funding amount requested in US Dollars
    placeholder: ex. $50,000
  validations:
    required: true

- type: dropdown
  id: project_overview_category
  attributes:
    label: Category
    description: '[See Category Definitions](https://zcashcommunitygrants.org/categories)'
    options:
    - Infrastructure
    - Community
    - Education
    - Non-Wallet Applications
    - Integration
    - Wallets
    - Research & Development
    - Media
    - Zcash Protocol Extension
    - Dedicated Resource
    - Event Sponsorships
  validations:
    required: true

- type: dropdown
  id: project_overview_sponsorship
  attributes:
    label: Sponsorship Request
    description: Indicate if this is a sponsorship request rather than a standard grant application
    options:
    - 'Yes'
    - 'No'
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Team Information'

- type: textarea
  id: team_information_project_lead
  attributes:
    label: Project Lead
    description: Provide details about the primary person responsible for the project
    value: |
      Name:
      Role:
      Background:
      Responsibilities:
  validations:
    required: true

- type: textarea
  id: team_information_members
  attributes:
    label: Additional Team Members
    description: List all other team members and their roles in the project
    value: |
      1. Name:
         Role:
         Background:
         Responsibilities:
      2. Name:
         Role:
         Background:
         Responsibilities:
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Details'

- type: textarea
  id: project_details_summary
  attributes:
    label: Project Summary
    description: Provide a brief summary/elevator pitch of your project in 1-2 sentences
  validations:
    required: true

- type: textarea
  id: project_details_description
  attributes:
    label: Project Description
    description: Provide a comprehensive overview of the project and its goals
  validations:
    required: true

- type: textarea
  id: project_details_problem
  attributes:
    label: Proposed Problem
    description: Clearly identify the problem or challenge your project aims to address
  validations:
    required: true

- type: textarea
  id: project_details_solution
  attributes:
    label: Proposed Solution
    description: Explain how your project will solve the identified problem
  validations:
    required: true

- type: textarea
  id: project_details_format
  attributes:
    label: Solution Format
    description: Describe the format and deliverables of your solution (e.g., software, research paper, event)
  validations:
    required: true

- type: textarea
  id: project_details_dependencies
  attributes:
    label: Dependencies
    description: List any technical, resource, or other dependencies required for your project
  validations:
    required: true

- type: textarea
  id: project_details_technical
  attributes:
    label: Technical Approach
    description: Outline the technical methodology and tools you plan to use
  validations:
    required: true

- type: textarea
  id: project_details_collaboration
  attributes:
    label: Collaboration and Upstream Dependencies
    description: Describe any dependencies or collaborations with other individuals, teams, or organizations required for success
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Budget'

- type: input
  id: budget_hardware
  attributes:
    label: Hardware/Software Costs (USD)
    description: Total cost for all hardware and software needed
    placeholder: ex. $5,000
  validations:
    required: true

- type: textarea
  id: budget_hardware_justification
  attributes:
    label: Hardware/Software Justification
    description: Explain why these hardware/software costs are necessary for the project
  validations:
    required: true

- type: input
  id: budget_service
  attributes:
    label: Service Costs (USD)
    description: Total cost for any external services required
    placeholder: ex. $10,000
  validations:
    required: true

- type: textarea
  id: budget_service_justification
  attributes:
    label: Service Costs Justification
    description: Explain why these service costs are necessary for the project
  validations:
    required: true

- type: input
  id: budget_compensation
  attributes:
    label: Compensation Costs (USD)
    description: Total cost for team member compensation
    placeholder: ex. $35,000
  validations:
    required: true

- type: textarea
  id: budget_compensation_justification
  attributes:
    label: Compensation Costs Justification
    description: Provide details about team member compensation and rates
  validations:
    required: true

- type: input
  id: budget_total
  attributes:
    label: Total Budget (USD)
    description: Sum of all costs (should match requested grant amount)
    placeholder: ex. $50,000
  validations:
    required: true

- type: dropdown
  id: budget_previous_funding
  attributes:
    label: Previous Funding
    description: Indicate if you have received any previous funding from Zcash Community Grants
    options:
    - 'Yes'
    - 'No'
  validations:
    required: true

- type: textarea
  id: budget_previous_details
  attributes:
    label: Previous Funding Details
    description: If you received previous funding, provide details about past grants and their outcomes
  validations:
    required: true

- type: dropdown
  id: budget_other_sources
  attributes:
    label: Other Funding Sources
    description: Indicate if you have or plan to receive funding from other sources
    options:
    - 'Yes'
    - 'No'
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Risk Assessment'

- type: textarea
  id: risk_implementation
  attributes:
    label: Implementation Risks
    description: Identify and describe potential challenges or obstacles to successful implementation
  validations:
    required: true

- type: textarea
  id: risk_side_effects
  attributes:
    label: Potential Side Effects
    description: Describe any potential unintended consequences or negative impacts
  validations:
    required: true

- type: textarea
  id: risk_metrics
  attributes:
    label: Success Metrics
    description: Define how you will measure and evaluate the success of your project
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Schedule'

- type: textarea
  id: schedule_timeline
  attributes:
    label: Timeline Overview
    description: Provide a detailed timeline showing major project phases and deadlines
  validations:
    required: true

- type: input
  id: schedule_startup
  attributes:
    label: Startup Funding (USD)
    description: Amount needed to begin the project (if different from total amount)
    placeholder: ex. $10,000
  validations:
    required: true

- type: textarea
  id: schedule_startup_justification
  attributes:
    label: Startup Funding Justification
    description: Explain why startup funding is needed and how it will be used
  validations:
    required: true

- type: textarea
  id: schedule_milestones
  attributes:
    label: Milestone Details
    description: Break down the project into specific milestones with associated deliverables and timelines
    value: |
      1. Milestone 1
      - Title:
      - Amount (USD): $
      - Expected Start Date: (YYYY-MM-DD)
      - Expected Completion Date: (YYYY-MM-DD)
      - Estimated Hours: HHHH
      - Deliverables: (Provide a brief summary)
      - _Status: ("", "In Progress", "Complete", "Cancelled")

      2. Milestone 2
      - Title:
      - Amount (USD): $
      - Expected Start Date: (YYYY-MM-DD)
      - Expected Completion Date: (YYYY-MM-DD)
      - Estimated Hours: HHHH
      - Deliverables: (Provide a brief summary)
      - _Status: ("", "In Progress", "Complete", "Cancelled")
  validations:
    required: true

- type: textarea
  id: supporting_documents
  attributes:
    label: Supporting Documents
    description: Upload and describe any additional documents that support your application
    value: |
      - File Name 1: Brief description of the file contents
      - File Name 2: Brief description of the file contents
  validations:
    required: true
