name: Grant Application - (ID, Project Name)
description: Zcash Community Grants Application Form
body:

- type: markdown
  attributes:
    value: |
      Terms and Conditions

- type: checkboxes
  id: terms_and_conditions_checkboxes
  attributes:
    label: Terms and Conditions
    options:
    - I agree to the [Grant Agreement]() terms if funded
    - I agree to [Provide KYC information]() if funded above $50,000 USD
    - I agree to disclose conflicts of interest
    - I agree to adhere to the [Code of Conduct]()
    - I agree to post request details on the [Community Forum]()
    - _Link to this issue on forum (do after application has been submitted)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Applicant Information'

- type: input
  id: applicant_information_organization_name
  attributes:
    label: Organization Name
  validations:
    required: true

- type: input
  id: applicant_information_application_owners
  attributes:
    label: Application Owners (GitHub @Usernames)
  validations:
    required: true

- type: input
  id: applicant_information_how_did_you_learn_about_zcash_community_grants
  attributes:
    label: How did you learn about Zcash Community Grants
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Details'

- type: input
  id: project_details_project_name
  attributes:
    label: Project Name
  validations:
    required: true

- type: input
  id: project_details_requested_grant_amount
  attributes:
    label: Requested Grant Amount (USD)
  validations:
    required: true

- type: dropdown
  id: project_details_category
  attributes:
    label: Category
    description: '[See Category Definitions](https://zcashcommunitygrants.org/categories)'
    options:
    - Infrastructure
    - Community
    - Education
    - Non-Wallet Applications
    - Integration
    - Wallets
    - Research & Development
    - Media
    - Zcash Protocol Extension
    - Dedicated Resource
    - Event Sponsorships
  validations:
    required: true

- type: dropdown
  id: project_details_sponsorship_request
  attributes:
    label: Sponsorship Request
    options:
    - 'Yes'
    - 'No'
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Team Members'

- type: input
  id: team_members_name
  attributes:
    label: Name
  validations:
    required: true

- type: input
  id: team_members_background
  attributes:
    label: Background
  validations:
    required: true

- type: textarea
  id: team_members_team_members
  attributes:
    label: Team Members
    value: "1. Name:\n   - Role: \n   - Background: \n   - Responsibilities: \n2.\
      \ Name:\n   - Role: \n   - Background: \n   - Responsibilities: \n..."
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Summary'

- type: markdown
  attributes:
    value: '## Project Description'

- type: markdown
  attributes:
    value: '## Budget'

- type: input
  id: budget_amount1
  attributes:
    label: Amount (USD)
  validations:
    required: true

- type: textarea
  id: budget_justification1
  attributes:
    label: Justification
  validations:
    required: true

- type: input
  id: budget_amount2
  attributes:
    label: Amount (USD)
  validations:
    required: true

- type: textarea
  id: budget_justification2
  attributes:
    label: Justification
  validations:
    required: true

- type: input
  id: budget_amount3
  attributes:
    label: Amount (USD)
  validations:
    required: true

- type: dropdown
  id: budget_justification3
  attributes:
    label: Justification
  validations:
    required: true

- type: input
  id: budget_total_amount
  attributes:
    label: Total Amount (USD)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Funding'

- type: dropdown
  id: funding_previous_funding
  attributes:
    label: Previous Funding
    options:
    - 'Yes'
    - 'No'
  validations:
    required: true

- type: textarea
  id: funding_previous_funding_details
  attributes:
    label: Previous Funding Details
  validations:
    required: true

- type: dropdown
  id: funding_other_funding_sources
  attributes:
    label: Other Funding Sources
    options:
    - 'Yes'
    - 'No'
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Risks and Evaluation'

- type: markdown
  attributes:
    value: '## Project Timeline'

- type: markdown
  attributes:
    value: '## Milestones'

- type: textarea
  id: milestones_milestones
  attributes:
    label: Milestones
    value: "### Milestone 1\n- Title: \n- Amount (USD): $\n- Expected Start Date:\
      \ (YYYY-MM-DD)\n- Expected Completion Date: (YYYY-MM-DD)\n- Estimated Hours:\
      \ HHHH\n- Deliverables: (Provide a brief summary)\n- _Status: (\"\", \"In Progress\"\
      , \"Complete\", \"Cancelled\")\n\n### Milestone 2\n- Title:\n- Amount (USD):\
      \ $\n- Expected Start Date: (YYYY-MM-DD)\n- Expected Completion Date: (YYYY-MM-DD)\n\
      - Estimated Hours: HHHH\n- Deliverables: (Provide a brief summary)\n- _Status:\
      \ (\"\", \"In Progress\", \"Complete\", \"Cancelled\")\n..."
  validations:
    required: true

- type: markdown
  attributes:
    value: '## File Attachments'

- type: textarea
  id: file_attachments_file_attachments
  attributes:
    label: File Attachments
    value: '- File Name 1: Brief description of the file contents

      - File Name 2: Brief description of the file contents

      ...'
  validations:
    required: true

