name: Grant Application
description: Submit a grant application to Zcash Community Grants
title: Grant Application - (ID, Project Name)
labels:
- Grant Application
body:

- type: markdown
  attributes:
    value: '## Terms and Conditions'

- type: checkbox
  id: i_agree_to_the_[grant_agreement]()_terms_if_funded
  attributes:
    label: I agree to the [Grant Agreement]() terms if funded
  validations:
    required: true

- type: checkbox
  id: i_agree_to_[provide_kyc_information]()_if_funded_above_$50,000_usd
  attributes:
    label: I agree to [Provide KYC information]() if funded above $50,000 USD
  validations:
    required: true

- type: checkbox
  id: i_agree_to_disclose_conflicts_of_interest
  attributes:
    label: I agree to disclose conflicts of interest
  validations:
    required: true

- type: checkbox
  id: i_agree_to_adhere_to_the_[code_of_conduct]()
  attributes:
    label: I agree to adhere to the [Code of Conduct]()
  validations:
    required: true

- type: checkbox
  id: i_agree_to_post_request_details_on_the_[community_forum]()
  attributes:
    label: I agree to post request details on the [Community Forum]()
  validations:
    required: true

- type: checkbox
  id: _link_to_this_issue_on_forum_(do_after_application_has_been_submitted)
  attributes:
    label: _Link to this issue on forum (do after application has been submitted)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Applicant Information'

- type: input
  id: organization_name
  attributes:
    label: Organization Name
    description: ''
  validations:
    required: true

- type: input
  id: application_owners_(github_@usernames)
  attributes:
    label: Application Owners (GitHub @Usernames)
    description: ''
  validations:
    required: true

- type: input
  id: how_did_you_learn_about_zcash_community_grants
  attributes:
    label: How did you learn about Zcash Community Grants
    description: ''
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Details'

- type: input
  id: project_name
  attributes:
    label: Project Name
    description: ''
  validations:
    required: true

- type: number
  id: requested_grant_amount_(usd)
  attributes:
    label: Requested Grant Amount (USD)
    description: $
  validations:
    required: true

- type: dropdown
  id: category
  attributes:
    label: Category
    description: '[See Category Definitions](https://zcashcommunitygrants.org/categories)'
    options:
    - label: Infrastructure
      value: Infrastructure
    - label: Community
      value: Community
    - label: Education
      value: Education
    - label: Non-Wallet Applications
      value: Non-Wallet Applications
    - label: Integration
      value: Integration
    - label: Wallets
      value: Wallets
    - label: Research & Development
      value: Research & Development
    - label: Media
      value: Media
    - label: Zcash Protocol Extension
      value: Zcash Protocol Extension
    - label: Dedicated Resource
      value: Dedicated Resource
    - label: Event Sponsorships
      value: Event Sponsorships
  validations:
    required: true

- type: textarea
  id: sponsorship_request
  attributes:
    label: Sponsorship Request
    description: (Yes/No)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Team Members'

- type: input
  id: name
  attributes:
    label: Name
    description: ''
  validations:
    required: true

- type: input
  id: background
  attributes:
    label: Background
    description: ''
  validations:
    required: true

- type: textarea
  id: team_members
  attributes:
    label: Team Members
    description: 'Enter team members details in the following format:'
    value: "1. Name:\n   - Role: \n   - Background: \n   - Responsibilities: \n2.\
      \ Name:\n   - Role: \n   - Background: \n   - Responsibilities: \n..."
  validations:
    required: false

- type: markdown
  attributes:
    value: '## Project Summary'

- type: markdown
  attributes:
    value: '## Project Description'

- type: markdown
  attributes:
    value: '## Budget'

- type: number
  id: amount_(usd)
  attributes:
    label: Amount (USD)
    description: $
  validations:
    required: true

- type: textarea
  id: justification
  attributes:
    label: Justification
    description: (Provide a brief summary)
  validations:
    required: true

- type: number
  id: amount_(usd)
  attributes:
    label: Amount (USD)
    description: $
  validations:
    required: true

- type: textarea
  id: justification
  attributes:
    label: Justification
    description: (Provide a brief summary)
  validations:
    required: true

- type: number
  id: amount_(usd)
  attributes:
    label: Amount (USD)
    description: $
  validations:
    required: true

- type: textarea
  id: justification
  attributes:
    label: Justification
    description: (Provide a brief summary)
  validations:
    required: true

- type: number
  id: total_amount_(usd)
  attributes:
    label: Total Amount (USD)
    description: $
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Funding'

- type: textarea
  id: previous_funding
  attributes:
    label: Previous Funding
    description: (Yes/No)
  validations:
    required: true

- type: textarea
  id: previous_funding_details
  attributes:
    label: Previous Funding Details
    description: (If applicable)
  validations:
    required: true

- type: textarea
  id: other_funding_sources
  attributes:
    label: Other Funding Sources
    description: (Yes/No)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Risks and Evaluation'

- type: markdown
  attributes:
    value: '## Project Timeline'

- type: markdown
  attributes:
    value: '## Milestones'

- type: textarea
  id: milestones
  attributes:
    label: Milestones
    description: 'Enter milestones details in the following format:'
    value: "### Milestone 1\n- Title: \n- Amount (USD): $\n- Expected Start Date:\
      \ (YYYY-MM-DD)\n- Expected Completion Date: (YYYY-MM-DD)\n- Estimated Hours:\
      \ HHHH\n- Deliverables: (Provide a brief summary)\n- _Status: (\"\", \"In Progress\"\
      , \"Complete\", \"Cancelled\")\n### Milestone 2\n- Title:\n- Amount (USD): $\n\
      - Expected Start Date: (YYYY-MM-DD)\n- Expected Completion Date: (YYYY-MM-DD)\n\
      - Estimated Hours: HHHH\n- Deliverables: (Provide a brief summary)\n- _Status:\
      \ (\"\", \"In Progress\", \"Complete\", \"Cancelled\")\n..."
  validations:
    required: false

- type: markdown
  attributes:
    value: '## File Attachments'

- type: textarea
  id: file_attachments
  attributes:
    label: File Attachments
    description: 'Enter file attachments details in the following format:'
    value: '- File Name 1: Brief description of the file contents
      - File Name 2: Brief description of the file contents
      ...'
  validations:
    required: false
