name: Grant Application
description: Submit a grant application to Zcash Community Grants
title: Grant Application - (ID, Project Name)
labels:
- Grant Application
body:

- type: markdown
  attributes:
    value: '## Terms and Conditions'

- type: textarea
  id: terms_and_conditions
  attributes:
    label: Terms and Conditions
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Terms and Conditions'

- type: checkboxes
  id: terms_and_conditions_checkboxes
  attributes:
    label: Terms and Conditions
    options:
    - label: I agree to the [Grant Agreement]() terms if funded
    - label: I agree to [Provide KYC information]() if funded above $50,000 USD
    - label: I agree to disclose conflicts of interest
    - label: I agree to adhere to the [Code of Conduct]()
    - label: I agree to post request details on the [Community Forum]()
    - label: _Link to this issue on forum (do after application has been submitted)
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Applicant Information'

- type: input
  id: applicant_information_organization_name
  attributes:
    label: Organization Name
  validations:
    required: true

- type: input
  id: applicant_information_application_owners
  attributes:
    label: Application Owners (GitHub @Usernames)
  validations:
    required: true

- type: input
  id: applicant_information_how_did_you_learn_about_zcash_community_grants
  attributes:
    label: How did you learn about Zcash Community Grants
  validations:
    required: true

- type: markdown
  attributes:
    value: '## Project Details'

- type: input
  id: project_details_project_name
  attributes:
    label: Project Name
  validations:
    required: true
