name: 'Grant Application - (ID, Project Name)
description: Zcash Community Grants Application Form
body:

- type: markdown
  attributes:
    value: |
      Terms and Conditions

- type: input
  id: applicant_information_organization_name
  attributes:
    label: Organization Name
  validations:
    required: true
