name: Testing
description: Please fill out this form to apply for a grant.
title: "[Grant Application]: {{project_name}}"
labels: grant-application
assignees:

body:
  - type: markdown
    attributes:
      value: |
        # Grant Application Template

        Please fill out all the sections below to apply for a grant.

  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Enter the name of your project
      placeholder: e.g., Zcash Wallet Improvement
    validations:
      required: true

  - type: input
    id: application_owners
    attributes:
      label: Application Owners (GitHub @Usernames)
      description: List the GitHub usernames of the application owners
      placeholder: e.g., @username1, @username2
    validations:
      required: true

  - type: textarea
    id: project_summary
    attributes:
      label: Project Summary
      description: Provide a brief summary of your project in 1-2 sentences
      placeholder: Write your summary here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Project Category
      description: Select the category that best describes your project
      options:
        - Infrastructure
        - Community
        - Education
        - Non-Wallet Applications
        - Integration
        - Wallets
        - Research & Development
        - Media
        - Zcash Protocol Extension
        - Dedicated Resource
        - Event Sponsorships
        - Wallets & Infrastructure
    validations:
      required: true

  - type: input
    id: requested_amount
    attributes:
      label: Requested Grant Amount (USD)
      description: Enter the total amount you are requesting in USD
      placeholder: e.g., 50000
    validations:
      required: true

  - type: textarea
    id: project_description
    attributes:
      label: Project Description
      description: Provide an overview of your project, including the proposed problem, solution, and technical approach
      placeholder: Write your project description here...
    validations:
      required: true

  - type: textarea
    id: technical_approach
    attributes:
      label: Technical Approach
      description: Describe your technical approach
      placeholder: Write your technical approach here...
    validations:
      required: true

  - type: textarea
    id: budget_breakdown
    attributes:
      label: Budget Breakdown
      description: Provide a detailed breakdown of your budget
      placeholder: Include hardware/software, services, compensation, etc.
    validations:
      required: true

  - type: textarea
    id: project_timeline
    attributes:
      label: Project Timeline
      description: Provide a detailed project timeline
      placeholder: Outline your project timeline here...
    validations:
      required: true

  - type: textarea
    id: milestones
    attributes:
      label: Milestones
      description: List your project milestones, including title, amount, expected dates, and deliverables
      placeholder: |
        ### Milestone 1
        - Title:
        - Amount: $
        - Expected Start Date: YYYY-MM-DD
        - Expected Completion Date: YYYY-MM-DD
        - Deliverables:

        ### Milestone 2
        - Title:
        - Amount: $
        - Expected Start Date: YYYY-MM-DD
        - Expected Completion Date: YYYY-MM-DD
        - Deliverables:
    validations:
      required: true

  - type: textarea
    id: team_members
    attributes:
      label: Team Members
      description: List the team members, their roles, backgrounds, and responsibilities
      placeholder: |
        ### Project Lead
        - Name:
        - Background:

        ### Additional Team Members
        1. **Name**:
           - Role:
           - Background:
           - Responsibilities:
        2. **Name**:
           - Role:
           - Background:
           - Responsibilities:
    validations:
      required: true

  - type: checkboxes
    id: terms_and_conditions
    attributes:
      label: Terms and Conditions
      description: Please agree to the terms and conditions
      options:
        - label: I agree to the [Grant Agreement]() terms if funded
          required: true
        - label: I agree to [Provide KYC information]() if funded above $50,000
          required: true
        - label: I agree to disclose conflicts of interest
          required: true
        - label: I agree to adhere to the [Code of Conduct]()
          required: true
        - label: I agree to post request details on the [Community Forum]()
          required: true

  - type: textarea
    id: referral_source
    attributes:
      label: How did you learn about Zcash Community Grants?
      description: Please let us know how you learned about us
      placeholder: Share your referral source here...
    validations:
      required: true

  - type: dropdown
    id: previous_funding
    attributes:
      label: Previous Funding
      description: Have you received previous funding?
      options:
        - Yes
        - No
    validations:
      required: true

  - type: textarea
    id: previous_funding_details
    attributes:
      label: Previous Funding Details
      description: Provide details of any previous funding received (if applicable)
      placeholder: Share details of previous funding here...
    validations:
      required: false

  - type: dropdown
    id: other_funding_sources
    attributes:
      label: Other Funding Sources
      description: Are there other funding sources?
      options:
        - Yes
        - No
    validations:
      required: true

  - type: textarea
    id: risks_and_evaluation
    attributes:
      label: Risks and Evaluation
      description: Describe potential execution risks, unintended consequences, and your evaluation plan
      placeholder: Outline risks and evaluation plan here...
    validations:
      required: true

  - type: textarea
    id: file_attachments
    attributes:
      label: File Attachments
      description: Provide links to any relevant file attachments and a brief description
      placeholder: |
        - [File Name 1](URL): Brief description of the file contents
        - [File Name 2](URL): Brief description of the file contents
    validations:
      required: false
