name: Testing
description: Please fill out this form to apply for a grant.
title: "Grant Application: project_name"
labels: grant-application

body:
  - type: markdown
    attributes:
      value: |
        # Grant Application Template

        Please fill out all the sections below to apply for a grant.

  - type: checkboxes
    id: terms_and_conditions
    attributes:
      label: Terms and Conditions
      description: Please agree to the terms and conditions
      options:
        - label: I agree to the [Grant Agreement]() terms if funded
          required: true
        - label: I agree to [Provide KYC information]() if funded above $50,000
          required: true
        - label: I agree to disclose conflicts of interest
          required: true
        - label: I agree to adhere to the [Code of Conduct]()
          required: true
        - label: I agree to post request details on the [Community Forum]()
          required: true

  - type: input
    id: application_owners
    attributes:
      label: Application Owners (GitHub @Usernames)
      description: List the GitHub usernames of the application owners
      placeholder: e.g., @username1, @username2
    validations:
      required: true

  - type: textarea
    id: referral_source
    attributes:
      label: How did you learn about Zcash Community Grants?
      description: Please let us know how you learned about us
      placeholder: Share your referral source here...
    validations:
      required: true

  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Enter the name of your project
      placeholder: e.g., Zcash Wallet Improvement
    validations:
      required: true

  - type: input
    id: last_updated
    attributes:
      label: Last Updated
      description: Enter the date of the last update (YYYY-MM-DD)
      placeholder: e.g., 2023-10-15
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Project Category
      description: Select the category that best describes your project
      options:
        - Infrastructure
        - Community
        - Education
        - Non-Wallet Applications
        - Integration
        - Wallets
        - Research & Development
        - Media
        - Zcash Protocol Extension
        - Dedicated Resource
        - Event Sponsorships
        - Wallets & Infrastructure
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Project Status
      description: Select the current status of your project
      options:
        - "New"
        - "Under Review"
        - "Approved"
        - "In Progress"
        - "Rejected"
        - "Complete"
        - "Cancelled"
    validations:
      required: true

  - type: dropdown
    id: sponsorship_request
    attributes:
      label: Sponsorship Request
      description: Is this a sponsorship request?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: project_image
    attributes:
      label: Project Image
      description: Provide a link to your project image (e.g., project_logo.png)
      placeholder: e.g., https://example.com/project_logo.png
    validations:
      required: false

  - type: textarea
    id: project_summary
    attributes:
      label: Project Summary
      description: Provide a brief summary of your project in 1-2 sentences
      placeholder: Write your summary here...
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Provide a brief overview of your project
      placeholder: Write your overview here...
    validations:
      required: true

  - type: textarea
    id: proposed_problem
    attributes:
      label: Proposed Problem
      description: Describe the problem your project addresses
      placeholder: Describe the problem here...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Describe your solution here...
    validations:
      required: true

  - type: textarea
    id: solution_format
    attributes:
      label: Solution Format
      description: Explain the format of your solution
      placeholder: Explain the format here...
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies for your project
      placeholder: List your dependencies here...
    validations:
      required: false

  - type: textarea
    id: technical_approach
    attributes:
      label: Technical Approach
      description: Describe your technical approach, including methods, technologies, and processes you will use
      placeholder: Write your technical approach here...
    validations:
      required: true

  - type: textarea
    id: collaboration_and_upstream_dependencies
    attributes:
      label: Collaboration and Upstream Dependencies
      description: Describe any collaborations or upstream dependencies
      placeholder: Describe collaborations and dependencies here...
    validations:
      required: false

  - type: input
    id: requested_amount
    attributes:
      label: Requested Grant Amount (USD)
      description: Enter the total amount you are requesting in USD
      placeholder: e.g., 50000
    validations:
      required: true

  - type: textarea
    id: hardware_software_budget
    attributes:
      label: Hardware/Software Budget
      description: Provide a breakdown of your hardware and software costs
      placeholder: Include details of hardware/software costs here...
    validations:
      required: false

  - type: textarea
    id: services_budget
    attributes:
      label: Services Budget
      description: Provide a breakdown of service-related costs
      placeholder: Include details of services costs here...
    validations:
      required: false

  - type: textarea
    id: compensation_budget
    attributes:
      label: Compensation Budget
      description: Provide a breakdown of compensation costs
      placeholder: Include compensation breakdown here...
    validations:
      required: false

  - type: textarea
    id: startup_funding
    attributes:
      label: Startup Funding
      description: Indicate if startup funding is required, and provide details if applicable
      placeholder: Specify if startup funding is needed, and add justification if yes...
    validations:
      required: false

  - type: textarea
    id: team_members
    attributes:
      label: Team Members
      description: List the team members, their roles, backgrounds, and responsibilities
      value: |
        ### Project Lead
        - Name:
        - Background:

        ### Additional Team Members
        1. **Name**:
           - Role:
           - Background:
           - Responsibilities:
        2. **Name**:
           - Role:
           - Background:
           - Responsibilities:
    validations:
      required: true

  - type: dropdown
    id: previous_funding
    attributes:
      label: Previous Funding
      description: Have you received previous funding?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: previous_funding_details
    attributes:
      label: Previous Funding Details
      description: Provide details of any previous funding received (if applicable)
      placeholder: Share details of previous funding here...
    validations:
      required: false

  - type: dropdown
    id: other_funding_sources
    attributes:
      label: Other Funding Sources
      description: Are there other funding sources?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: execution_risks
    attributes:
      label: Execution Risks
      description: Describe potential execution risks
      placeholder: Outline execution risks here...
    validations:
      required: true

  - type: textarea
    id: unintended_consequences
    attributes:
      label: Unintended Consequences
      description: Describe potential unintended consequences
      placeholder: Describe unintended consequences here...
    validations:
      required: true

  - type: textarea
    id: evaluation_plan
    attributes:
      label: Evaluation Plan
      description: Outline your evaluation plan
      placeholder: Outline your evaluation plan here...
    validations:
      required: true

  - type: textarea
    id: project_timeline
    attributes:
      label: Project Timeline
      description: Provide a detailed project timeline with stages and key dates
      placeholder: Outline your project timeline here...
    validations:
      required: true

  - type: textarea
    id: milestones
    attributes:
      label: Milestones
      description: List your project milestones, including title, amount, expected dates, and deliverables
      value: |
        ### Milestone 1
        - Title:
        - Amount: $
        - Expected Start Date: YYYY-MM-DD
        - Expected Completion Date: YYYY-MM-DD
        - Estimated Hours:
        - Deliverables:

        ### Milestone 2
        - Title:
        - Amount: $
        - Expected Start Date: YYYY-MM-DD
        - Expected Completion Date: YYYY-MM-DD
        - Estimated Hours:
        - Deliverables:
    validations:
      required: true

  - type: textarea
    id: file_attachments
    attributes:
      label: File Attachments
      description: Provide links to any relevant file attachments and a brief description
      placeholder: |
        - [File Name 1](URL): Brief description of the file contents
        - [File Name 2](URL): Brief description of the file contents
    validations:
      required: false
