name: 'Save Issue Content'
description: 'Saves issue content to a file with proper formatting'

inputs:
  issue-body:
    description: 'Content of the issue'
    required: true
  issue-title:
    description: 'Title of the issue'
    required: true
  issue-number:
    description: 'Issue number'
    required: true
  author:
    description: 'Issue author'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Save issue content
      shell: bash
      run: |
        mkdir -p _grants
        
        FILENAME=$(echo "100${{ inputs.issue-number }}-${{ inputs.issue-title }}" | tr ' ' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]').md
        
        cat > "_grants/$FILENAME" << EOL
        ---
        title: "${{ inputs.issue-title }}"
        issue_number: ${{ inputs.issue-number }}
        created_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        author: "${{ inputs.author }}"
        protected: true
        ---

        ${{ inputs.issue-body }}
        EOL
