name: 'ZCG Grant Notice'
description: 'Posts ZCG grant application instructions and requirements'

inputs:
  token:
    description: 'GitHub token'
    required: true
  issue-number:
    description: 'Issue number'
    required: true
  repo-owner:
    description: 'Repository owner'
    required: true
  repo-name:
    description: 'Repository name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Post Grant Notice
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const noticeMessage = `Thank you for submitting a ZCG grant application. Please [post a link to this issue on the Zcash Community Forums](https://forum.zcashcommunity.com/c/Grants/Applications/) for community feedback and to answer questions from the community and Zcash Community Grants committee. A forum post is required for the committee to review your proposal. If you are new to the Zcash Forum and are unable to make a forum post please send a DM to moderators on the forum to ask them to give you posting access.

          The committee reviews grant applications on an ongoing basis and may request proposal revisions for incomplete applications or proposals that do not adhere to the [Code of Conduct](https://forum.zcashcommunity.com/faq). You can expect to hear from the committee in 2-4 weeks from the date you submit your application via the forum thread for your grant.

          Please contact grants@financialprivacyfoundation.org at any time with questions.`;

          await github.rest.issues.createComment({
            owner: inputs.repo-owner,
            repo: inputs.repo-name,
            issue_number: inputs.issue-number,
            body: noticeMessage
          });
