name: 'Protection Labels and Notice'
description: 'Applies protection labels and creates notices for protected content'

inputs:
  token:
    description: 'GitHub token'
    required: true
  issue-number:
    description: 'Issue number'
    required: true
  repo-owner:
    description: 'Repository owner'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check and Apply Protection Labels
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const issue = await github.rest.issues.get({
            owner: '${{ inputs.repo-owner }}',
            repo: '${{ inputs.repo-name }}',
            issue_number: ${{ inputs.issue-number }}
          });
          
          const hasProtectionLabel = issue.data.labels.some(label => 
            label.name === 'content-protected'
          );
          
          if (!hasProtectionLabel) {
            await github.rest.issues.addLabels({
              owner: '${{ inputs.repo-owner }}',
              repo: '${{ inputs.repo-name }}',
              issue_number: ${{ inputs.issue-number }},
              labels: ['content-protected']
            });
          }

    - name: Post ZCG Grant Notice
      uses: ./.github/actions/zcg-grant-notice
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ inputs.issue-number }}
        repo-owner: ${{ inputs.repo-owner }}
        repo-name: ${{ inputs.repo-name }}
        body: |
          ## 📝 Grant Application Notice
          
          Thank you for submitting your grant application. Your application is now being processed.
          
          Please note:
          - The content of this issue is protected and any changes will be monitored
          - A snapshot of your application has been created
          - The ZCG committee will review your application

    - name: Create Change Notice
      if: github.event_name == 'issues' && github.event.action == 'edited'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const changeNotice = `## ⚠️ Content Change Detected

          The protected content of this issue has been modified.
          - The existing snapshot PR has been updated
          - Maintainers will review these changes
          
          @${REPO_OWNER} Please review these changes.`;

          await github.rest.issues.createComment({
            owner: '${{ inputs.repo-owner }}',
            repo: '${{ inputs.repo-name }}',
            issue_number: ${{ inputs.issue-number }},
            body: changeNotice
          });
