name: 'Protection Labels and Notice'
description: 'Applies protection labels and creates notices for protected content'

inputs:
  token:
    description: 'GitHub token'
    required: true
  issue-number:
    description: 'Issue number'
    required: true
  repo-owner:
    description: 'Repository owner'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check and Apply Protection Labels
      uses: actions/github-script@v7
      env:
        REPO_OWNER: ${{ inputs.repo-owner }}
        REPO_NAME: ${{ inputs.repo-name }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        PR_NUMBER: ${{ inputs.pr-number }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { REPO_OWNER, REPO_NAME, ISSUE_NUMBER, PR_NUMBER } = process.env
          
          const issue = await github.rest.issues.get({
            owner: REPO_OWNER,
            repo: REPO_NAME, 
            issue_number: ISSUE_NUMBER
          });
          
          const hasProtectionLabel = issue.data.labels.some(label => 
            label.name === 'content-protected'
          );
          
          if (!hasProtectionLabel) {
            await github.rest.issues.addLabels({
              owner: REPO_OWNER,
              repo: REPO_NAME,
              issue_number: ISSUE_NUMBER,
              labels: ['content-protected']
            });

            const protectionMessage = `# 🔒 Content Protection Notice

            This issue's content has been saved and is now protected. A snapshot has been created in PR #${PR_NUMBER}.

            ## What this means:
            - The original content is preserved in the repository
            - While the content can still be edited, changes will be monitored
            - Each edit will trigger a new snapshot PR
            
            ## To make changes:
            1. Edit the issue content as needed
            2. A new PR will automatically be created with your changes
            3. Maintainers will review the changes

            💬 Comments remain open for discussion.
            
            If you need to make substantial changes, please discuss with maintainers first.`;

            await github.rest.issues.createComment({
              owner: REPO_OWNER,
              repo: REPO_NAME,
              issue_number: ISSUE_NUMBER,
              body: protectionMessage
            });
          }

    - name: Create Change Notice
      if: github.event_name == 'issues' && github.event.action == 'edited'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const changeNotice = `## ⚠️ Content Change Detected

          The protected content of this issue has been modified.
          - The existing snapshot PR has been updated
          - Maintainers will review these changes
          
          @${REPO_OWNER} Please review these changes.`;

          await github.rest.issues.createComment({
            owner: REPO_OWNER,
            repo: REPO_NAME,
            issue_number: ISSUE_NUMBER,
            body: changeNotice
          });
