name: Grant Review Process
on:
  issues:
    types: [labeled, edited]

jobs:
  process-grant:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'Ready for ZCG Review') ||
      (github.event.action == 'edited' && contains(github.event.issue.labels.*.name, 'Ready for ZCG Review'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Save Content
        uses: ./.github/actions/save-content
        with:
          issue-body: ${{ github.event.issue.body }}
          issue-title: ${{ github.event.issue.title }}
          issue-number: ${{ github.event.issue.number }}
          author: ${{ github.event.issue.user.login }}

      - name: Manage PR
        id: pr-management
        uses: ./.github/actions/pr-management
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: "grant-${{ github.event.issue.number }}"
          issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}

      - name: Apply Protection Labels and Notice
        uses: ./.github/actions/protection-labels-notice
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          repo-owner: ${{ github.repository_owner }}
          repo-name: ${{ github.event.repository.name }}
          pr-number: ${{ steps.pr-management.outputs.pr_number }}

      - name: Monitor Changes
        if: github.event.action == 'edited'
        uses: ./.github/actions/monitor-changes
        with:
          issue-number: ${{ github.event.issue.number }}
          repository-owner: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge if new grant
        if: github.event.action == 'labeled'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head "grant-${{ github.event.issue.number }}" --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --auto --merge
          fi
