name: Manual Hello World
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: true
        default: 'Hello World!'
      environment:
        description: 'Environment to run the workflow in'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: |
          echo "Message: ${{ github.event.inputs.message }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Workflow triggered at: $(date)"
          echo "Repository: ${{ github.repository }}"
          
      - name: Print Job Status
        run: |
          echo "Job completed successfully!"
